### ISSUE TITLE
PhiX sequences

### ISSUE THREAD

**Issue by mgandal** [bfosso/MetaShot#5]
The Phix_cleaner.py script appears to require a phix bowtie2 index but it is not clear from the README exactly how that should be formatted or where that should be located.

**Comment by transcript** [comment]
Also having this issue.  A MetaShot run fails with the error 
`file /home/dnanexus/phix_removal_1/R1_no_phix.fastq is missing`.

**Comment by bfosso** [comment]
Currently we are working to update the reference collection used in MetaShot and probably something goes wrong. In order to bypass this issue I attach here the Phix reference.

[PhiX.fasta.gz](https://github.com/bfosso/MetaShot/files/2269305/PhiX.fasta.gz)

Moreover, in the Phix folder there is a script called build_index.sh. You need just to execute it by typing:
_bash build_index.sh_
